In [5]:
import pandas as pd

In [6]:
path = "/content/Online_Retail.csv"

In [7]:
df = pd.read_csv(path, encoding='windows-1254')

In [8]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
247226,558760,22938,CUPCAKE LACE PAPER SET 6,6,7/3/11 12:38,1.95,16918.0,United Kingdom
247227,558760,72351B,SET/6 PINK BUTTERFLY T-LIGHTS,6,7/3/11 12:38,2.10,16918.0,United Kingdom
247228,558760,72351A,SET/6 TURQUOISE BUTTERFLY T-LIGHTS,6,7/3/11 12:38,2.10,16918.0,United Kingdom
247229,558760,20719,WOODLAND CHARLOTTE BAG,5,7/3/11 12:38,0.85,16918.0,United Kingdom
247230,558760,20723,STRAWBERRY CHARLOTTE BAG,10,7/3/11 12:38,0.85,16918.0,United K

In [9]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247231 entries, 0 to 247230
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    247231 non-null  object
 1   StockCode    247231 non-null  object
 2   Description  246300 non-null  object
 3   Quantity     247231 non-null  int64
 4   InvoiceDate  247231 non-null  object
 5   UnitPrice    247231 non-null  float64
 6   CustomerID   178066 non-null  float64
 7   Country      247231 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 15.1+ MB

In [11]:
df.isnull().sum()

InvoiceNo          0
StockCode          0
Description      931
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     69165
Country            0
dtype: int64

In [12]:
df_cleaned = df.dropna()

In [13]:
df_cleaned

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
247226,558760,22938,CUPCAKE LACE PAPER SET 6,6,7/3/11 12:38,1.95,16918.0,United Kingdom
247227,558760,72351B,SET/6 PINK BUTTERFLY T-LIGHTS,6,7/3/11 12:38,2.10,16918.0,United Kingdom
247228,558760,72351A,SET/6 TURQUOISE BUTTERFLY T-LIGHTS,6,7/3/11 12:38,2.10,16918.0,United Kingdom
247229,558760,20719,WOODLAND CHARLOTTE BAG,5,7/3/11 12:38,0.85,16918.0,United Kingdom
247230,558760,20723,STRAWBERRY CHARLOTTE BAG,10,7/3/11 12:38,0.85,16918.0,United K

In [14]:
df_sorted = df.sort_values(by= "Quantity", ascending=False)
df_sorted

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1/18/11 10:01,1.04,12346.0,United Kingdom
74614,542504,37413,NaN,5568,1/28/11 12:03,0.00,NaN,United Kingdom
206121,554868,22197,SMALL POPCORN HOLDER,4300,5/27/11 10:52,0.72,13135.0,United Kingdom
220843,556231,85123A,?,4000,6/9/11 15:04,0.00,NaN,United Kingdom
97432,544612,22053,EMPIRE DESIGN ROSETTE,3906,2/22/11 10:43,0.82,18087.0,United Kingdom
...,...,...,...,...,...,...,...,...
225528,556687,23003,Printing smudges/thrown away,-9058,6/14/11 10:36,0.00,NaN,United Kingdom
4287,C536757,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,-9360,12/2/10 14:23,0.03,15838.0,United Kingdom
225530,556691,23005,printing smudges/thrown away,-9600,6/14/11 10:37,0.00,NaN,United Kingdom
225529,556690,23005,printing smudges/thrown away,-9600,6/14/11 10:37,0.00,NaN,United Kingdom
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,1/18/11 10:17,1.04,12346.0,United Kingdom

In [17]:
df_with_out = df_sorted[df_sorted['Country'] != 'United Kingdom']
df_with_out

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
19871,537899,22328,ROUND SNACK BOXES SET OF 4 FRUITS,1488,12/9/10 10:44,2.55,12755.0,Japan
6365,536890,17084R,ASSORTED INCENSE PACK,1440,12/3/10 11:48,0.16,14156.0,EIRE
63444,541570,21212,PACK OF 72 RETROSPOT CAKE CASES,1440,1/19/11 12:34,0.42,14646.0,Netherlands
186820,552883,21212,PACK OF 72 RETROSPOT CAKE CASES,1200,5/12/11 10:13,0.42,14646.0,Netherlands
204198,554642,22243,5 HOOK HANGER RED MAGIC TOADSTOOL,960,5/25/11 12:19,1.45,14646.0,Netherlands
...,...,...,...,...,...,...,...,...
102732,C545033,22699,ROSES REGENCY TEACUP AND SAUCER,-120,2/25/11 16:26,2.55,14156.0,EIRE
115928,C546162,85178,VICTORIAN SEWING KIT,-144,3/10/11 9:53,1.25,17404.0,Sweden
102733,C545033,22630,DOLLY GIRL LUNCH BOX,-192,2/25/11 16:26,1.65,14156.0,EIRE
30078,C538847,85232B,SET OF 3 BABUSHKA STACKING TINS,-240,12/14/10 13:27,4.95,17404.0,Sweden
144190,C548731,22328,ROUND SNACK BOXES SET OF 4 FRUITS,-624,4/4/11 10:12,2.55,12755.0,Japan

Warning: total number of rows (20249) exceeds max_rows (20000). Limiting to first (20000) rows.

In [69]:
#2) Create a Dictionary with the 10 countries that have the most 'Quantity'
# ordered except UK

qountity = df_with_out['Quantity'].iloc[:10].tolist()
qountity

[1488, 1440, 1440, 1200, 960, 768, 640, 640, 600, 600]

In [70]:
country = df_with_out['Country'].iloc[:10].tolist()
country

['Japan',
 'EIRE',
 'Netherlands',
 'Netherlands',
 'Netherlands',
 'Sweden',
 'Netherlands',
 'Netherlands',
 'Australia',
 'Germany']

In [72]:
my_dict = {k: v for k, v in zip(qountity, country)}
my_dict

{1488: 'Japan',
 1440: 'Netherlands',
 1200: 'Netherlands',
 960: 'Netherlands',
 768: 'Sweden',
 640: 'Netherlands',
 600: 'Germany'}

In [ ]:
df_sorted.dropna()

In [79]:
from datetime import datetime

In [83]:
from pandas.core.internals.construction import dataclasses_to_dicts
date_one = input("Please enter a date (YYYY-MM-DD): ")
date_two = input("Please enter a date (YYYY-MM-DD): ")


date1 = datetime.strptime(date_one, "%Y-%m-%d")
date2 = datetime.strptime(date_two, "%Y-%m-%d")


# time_difference = date1 - date2
# days_difference = time_difference.days


sales_df = df_cleaned[(df_cleaned['InvoiceDate'] >= date1) & (df_cleaned['InvoiceDate'] <= date2)]


sales_df['Quantity'].sum()

Please enter a date (YYYY-MM-DD): 2011-1-1
Please enter a date (YYYY-MM-DD): 2011-2-2

TypeError: ignored

In [ ]:
#4) Find each Countries Total SALE to find which Countries
# is highest potential customer

max_sell = df_sorted.groupby('Country')['Quantity'].sum()
max_sell

In [28]:
high_quantity = df_cleaned['Quantity'].idxmax()
high_quantity

61619

In [ ]:
df_sorted.groupby('Country')['Quantity'].sum().reset_index()
high = df_sorted.groupby('Country')['Quantity'].sum().reset_index()

In [31]:
high.sort_values(by= 'Quantity', ascending=False).iloc[0]

Country     United Kingdom
Quantity           1871221
Name: 36, dtype: object

In [ ]:
#5) Which Customer Id has highest purchase in
#quantity and total and find out the country of it


df_sorted.groupby('CustomerID')['Quantity'].sum().reset_index()
df_sorted.groupby('CustomerID')['Quantity'].sum().reset_index().sort_values(by='Quantity', ascending= False)
low = df_sorted.groupby('CustomerID')['Quantity'].sum().reset_index().sort_values(by='Quantity', ascending= True)

In [75]:
low.sort_values(by= 'Quantity', ascending=False).iloc[0]

CustomerID    14646.0
Quantity      97418.0
Name: 1180, dtype: float64

In [47]:
df_sorted[df_sorted['CustomerID'] == 15838.0].iloc[7, -1]

'United Kingdom'

In [46]:
#7) Find the biggest order In Sale (Cost) which country was the order from and fiind total purchase
 #(Cost) done by that customer ID

low.sort_values(by= 'Quantity', ascending=False).iloc[0]

CustomerID    14646.0
Quantity      97418.0
Name: 1180, dtype: float64

In [64]:
df_sorted[df_sorted['CustomerID'] == 14646.0].iloc[7, -1]

'Netherlands'

In [60]:
# 8) Find how many different customers are available
#  for each country save the count in dictionary also
# return countries with highest and lowest customer count

customer_counts = {}
for country, group in df_sorted.groupby('Country'):
    customer_counts[country] = group['CustomerID'].nunique()

max(customer_counts, key=customer_counts.get)

'United Kingdom'

In [61]:
customer_counts = {}
for country, group in df_sorted.groupby('Country'):
    customer_counts[country] = group['CustomerID'].nunique()

min(customer_counts, key=customer_counts.get)

'Hong Kong'

In [63]:
# 9) Find which stock code was ordered the most by each country

stock_by_country = df_sorted.groupby(['Country', 'StockCode']).size().reset_index(name='Count')
stock_by_country = stock_by_country.sort_values(by='Count', ascending=False)
stock_by_country.drop_duplicates('Country')

                    Country StockCode  Count
12120        United Kingdom    85123A   1282
5458                Germany      POST    172
4344                 France      POST    149
3079                   EIRE        C2     50
1006                Belgium      POST     50
8325                  Spain      POST     28
6832            Netherlands      POST     22
7574               Portugal      POST     17
8920            Switzerland      POST     16
3382                Finland      POST     12
6044                  Italy      POST     10
7679              Singapore         M     10
8463                 Sweden      POST     10
535                 Austria      POST      9
7096                 Norway         M      6
167               Australia     22382      6
6147                  Japan     22661      5
7109                 Poland     21232      5
1840                Denmark      POST      5
1254        Channel Islands     22690      5
5718                Iceland     22375      4
5628              Hong Kong     22452      4
1560                 Cyprus     22804      4
549                 Bahrain    72802B      3
6309                  Malta    72807C      2
6274              Lithuania     22751      2
7576           Saudi Arabia     22361      2
1683         Czech Republic     22231      2
3086     European Community     22312      2
8924                    USA     22129      1
12651           Unspecified     22585      1
8943   United Arab Emirates     20961      1
8973               United K     20723      1
1049                 Canada     21622      1
1033                 Brazil     23052      1
6234                Lebanon     22922      1
5806                 Israel     47566      1
5470                 Greece     21669      1

0

In [73]:
country_total_sales = df_sorted.groupby('Country')['Quantity'].sum().reset_index()

# Find the country with the highest total sales
highest_sales_country = country_total_sales[country_total_sales['Quantity'] == country_total_sales['Quantity'].max()]

In [74]:
highest_sales_country

           Country  Quantity
36  United Kingdom   1871221