In [2]:
import pandas as pd

In [3]:
path = "/content/Online_Retail.csv"

In [4]:
df = pd.read_csv(path, encoding='windows-1252')
# df = pd.read_csv(path, on_bad_lines='skip')
# df = pd.read_csv(path, encoding='unicode_escape')

In [5]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France

In [6]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [8]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [9]:
df_cleaned = df.dropna()

In [10]:
df_cleaned

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France

In [11]:
df_sorted = df.sort_values(by= "Quantity", ascending=False)
df_sorted

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,12/9/11 9:15,2.08,16446.0,United Kingdom
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1/18/11 10:01,1.04,12346.0,United Kingdom
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,11/25/11 15:57,0.00,13256.0,United Kingdom
74614,542504,37413,NaN,5568,1/28/11 12:03,0.00,NaN,United Kingdom
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,10/27/11 12:26,0.21,12901.0,United Kingdom
...,...,...,...,...,...,...,...,...
4287,C536757,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,-9360,12/2/10 14:23,0.03,15838.0,United Kingdom
225530,556691,23005,printing smudges/thrown away,-9600,6/14/11 10:37,0.00,NaN,United Kingdom
225529,556690,23005,printing smudges/thrown away,-9600,6/14/11 10:37,0.00,NaN,United Kingdom
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,1/18/11 10:17,1.04,12346.0,United Kingdom
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,12/9/11 9:27,2.08,16446.0,United Kingdom

In [12]:
df_with_out = df_sorted[df_sorted['Country'] != 'United Kingdom']
df_with_out

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
421601,573003,23084,RABBIT NIGHT LIGHT,2400,10/27/11 12:11,2.08,14646.0,Netherlands
511421,579498,23084,RABBIT NIGHT LIGHT,2040,11/29/11 15:52,1.79,12798.0,Japan
409248,572052,22595,GINGHAM HEART DECORATION,1728,10/20/11 12:26,0.72,14646.0,Netherlands
19871,537899,22328,ROUND SNACK BOXES SET OF 4 FRUITS,1488,12/9/10 10:44,2.55,12755.0,Japan
6365,536890,17084R,ASSORTED INCENSE PACK,1440,12/3/10 11:48,0.16,14156.0,EIRE
...,...,...,...,...,...,...,...,...
402438,C571499,72802C,VANILLA SCENT CANDLE JEWELLED BOX,-288,10/17/11 15:07,1.25,12454.0,Spain
505541,C579090,84598,BOYS ALPHABET IRON ON PATCHES,-288,11/28/11 10:48,0.21,12427.0,Germany
290364,C562375,22950,36 DOILIES VINTAGE CHRISTMAS,-288,8/4/11 14:46,1.25,14911.0,EIRE
319804,C564899,M,Manual,-480,8/31/11 11:31,0.22,14646.0,Netherlands
144190,C548731,22328,ROUND SNACK BOXES SET OF 4 FRUITS,-624,4/4/11 10:12,2.55,12755.0,Japan

In [13]:
#2) Create a Dictionary with the 10 countries that have the most 'Quantity'
# ordered except UK

qountity = df_with_out['Quantity'].iloc[:10].tolist()
qountity

[2400, 2040, 1728, 1488, 1440, 1440, 1440, 1200, 1152, 960]

In [14]:
country = df_with_out['Country'].iloc[:10].tolist()
country

['Netherlands',
 'Japan',
 'Netherlands',
 'Japan',
 'EIRE',
 'Netherlands',
 'Netherlands',
 'Netherlands',
 'Australia',
 'Australia']

In [15]:
my_dict = {k: v for k, v in zip(qountity, country)}
my_dict

{2400: 'Netherlands',
 2040: 'Japan',
 1728: 'Netherlands',
 1488: 'Japan',
 1440: 'Netherlands',
 1200: 'Netherlands',
 1152: 'Australia',
 960: 'Australia'}

In [41]:
df_sorted.dropna()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,12/9/11 9:15,2.08,16446.0,United Kingdom
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1/18/11 10:01,1.04,12346.0,United Kingdom
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,11/25/11 15:57,0.00,13256.0,United Kingdom
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,10/27/11 12:26,0.21,12901.0,United Kingdom
206121,554868,22197,SMALL POPCORN HOLDER,4300,5/27/11 10:52,0.72,13135.0,United Kingdom
...,...,...,...,...,...,...,...,...
160144,C550456,21175,GIN + TONIC DIET METAL SIGN,-2000,4/18/11 13:08,1.85,15749.0,United Kingdom
160145,C550456,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,-3114,4/18/11 13:08,2.10,15749.0,United Kingdom
4287,C536757,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,-9360,12/2/10 14:23,0.03,15838.0,United Kingdom
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,1/18/11 10:17,1.04,12346.0,United Kingdom
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,12/9/11 9:27,2.08,16446.0,United Kingdom

Warning: total number of rows (406829) exceeds max_rows (20000). Limiting to first (20000) rows.

In [44]:
df_sorted.InvoiceDate

540421   2011-12-09 09:15:00
61619    2011-01-18 10:01:00
502122   2011-11-25 15:57:00
74614    2011-01-28 12:03:00
421632   2011-10-27 12:26:00
                 ...
4287     2010-12-02 14:23:00
225530   2011-06-14 10:37:00
225529   2011-06-14 10:37:00
61624    2011-01-18 10:17:00
540422   2011-12-09 09:27:00
Name: InvoiceDate, Length: 541909, dtype: datetime64[ns]

In [17]:
from datetime import datetime

# 3)  Find Total Sale between two dates entered by user

In [59]:

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], format='%m/%d/%y %H:%M')


start_date_input = input("Enter the start date (YYYY-MM-DD): ")
end_date_input = input("Enter the end date (YYYY-MM-DD): ")

start_date = pd.to_datetime(start_date_input)
end_date = pd.to_datetime(end_date_input)


filtered_df = df[(df['InvoiceDate'] >= start_date) & (df['InvoiceDate'] <= end_date)]


total_sale = filtered_df['Quantity'].sum()

print(f"Total sale between {start_date} and {end_date}: ${total_sale:.2f}")

Enter the start date (YYYY-MM-DD): 2010-12-28
Enter the end date (YYYY-MM-DD): 2011-3-29
Total sale between 2010-12-28 00:00:00 and 2011-03-29 00:00:00: $870458.00

In [19]:
#4) Find each Countries Total SALE to find which Countries
# is highest potential customer

max_sell = df_sorted.groupby('Country')['Quantity'].sum()
max_sell

Country
Australia                 83653
Austria                    4827
Bahrain                     260
Belgium                   23152
Brazil                      356
Canada                     2763
Channel Islands            9479
Cyprus                     6317
Czech Republic              592
Denmark                    8188
EIRE                     142637
European Community          497
Finland                   10666
France                   110480
Germany                  117448
Greece                     1556
Hong Kong                  4769
Iceland                    2458
Israel                     4353
Italy                      7999
Japan                     25218
Lebanon                     386
Lithuania                   652
Malta                       944
Netherlands              200128
Norway                    19247
Poland                     3653
Portugal                  16180
RSA                         352
Saudi Arabia                 75
Singapore                  5234
Spain                     26824
Sweden                    35637
Switzerland               30325
USA                        1034
United Arab Emirates        982
United Kingdom          4263829
Unspecified                3300
Name: Quantity, dtype: int64

In [20]:
high_quantity = df_cleaned['Quantity'].idxmax()
high_quantity

540421

In [21]:
df_sorted.groupby('Country')['Quantity'].sum().reset_index()
high = df_sorted.groupby('Country')['Quantity'].sum().reset_index()

In [22]:
high.sort_values(by= 'Quantity', ascending=False).iloc[0]

Country     United Kingdom
Quantity           4263829
Name: 36, dtype: object

In [23]:
#5) Which Customer Id has highest purchase in
#quantity and total and find out the country of it


df_sorted.groupby('CustomerID')['Quantity'].sum().reset_index()
df_sorted.groupby('CustomerID')['Quantity'].sum().reset_index().sort_values(by='Quantity', ascending= False)
low = df_sorted.groupby('CustomerID')['Quantity'].sum().reset_index().sort_values(by='Quantity', ascending= True)

In [24]:
low.sort_values(by= 'Quantity', ascending=False).iloc[0]

CustomerID     14646.0
Quantity      196719.0
Name: 1703, dtype: float64

In [25]:
df_sorted[df_sorted['CustomerID'] == 15838.0].iloc[7, -1]

'United Kingdom'

In [26]:
#7) Find the biggest order In Sale (Cost) which country was the order from and fiind total purchase
 #(Cost) done by that customer ID

low.sort_values(by= 'Quantity', ascending=False).iloc[0]

CustomerID     14646.0
Quantity      196719.0
Name: 1703, dtype: float64

In [ ]:
df_sorted[df_sorted['CustomerID'] == 14646.0].iloc[7, -1]

'Netherlands'

In [27]:
# 8) Find how many different customers are available
#  for each country save the count in dictionary also
# return countries with highest and lowest customer count

customer_counts = {}
for country, group in df_sorted.groupby('Country'):
    customer_counts[country] = group['CustomerID'].nunique()

max(customer_counts, key=customer_counts.get)

'United Kingdom'

In [28]:
customer_counts = {}
for country, group in df_sorted.groupby('Country'):
    customer_counts[country] = group['CustomerID'].nunique()

min(customer_counts, key=customer_counts.get)

'Hong Kong'

In [29]:
# 9) Find which stock code was ordered the most by each country

stock_by_country = df_sorted.groupby(['Country', 'StockCode']).size().reset_index(name='Count')
stock_by_country = stock_by_country.sort_values(by='Count', ascending=False)
stock_by_country.drop_duplicates('Country')

                    Country StockCode  Count
18962        United Kingdom    85123A   2215
8781                Germany      POST    383
7110                 France      POST    311
5057                   EIRE        C2    108
1700                Belgium      POST     98
13959                 Spain      POST     62
5567                Finland      POST     41
11120           Netherlands      POST     39
15198           Switzerland      POST     33
12621              Portugal      POST     30
14220                Sweden      POST     24
11711                Norway      POST     20
9946                  Italy      POST     18
3083                Denmark      POST     14
12866             Singapore         M     14
906                 Austria      POST     14
296               Australia     22720     10
2478                 Cyprus     22423      8
11715                Poland     16016      7
2073        Channel Islands     22690      7
9970                  Japan     21218      7
9140                Iceland     22375      6
9109              Hong Kong         M      6
10278                 Malta     22768      5
9414                 Israel     23240      5
15236                   USA     22027      4
8919                 Greece      POST      4
19593           Unspecified     22150      4
2829         Czech Republic    84459A      3
920                 Bahrain    72802B      3
5109     European Community      POST      3
10214             Lithuania     20967      2
12681          Saudi Arabia     22361      2
1733                 Canada     10133      2
15362  United Arab Emirates     20961      1
1721                 Brazil     22699      1
10183               Lebanon     22722      1
12677                   RSA     85066      1

In [36]:

date_one = input("Please enter a date (YYYY-MM-DD): ")
date_two = input("Please enter a date (YYYY-MM-DD): ")

date1 = datetime.strptime(date_one, "%Y-%m-%d")
date2 = datetime.strptime(date_two, "%Y-%m-%d")

start_date = pd.to_datetime(date1)
end_date = pd.to_datetime(date2)

df_cleaned['InvoiceDate'] = pd.to_datetime(df_cleaned['InvoiceDate'])


sales_df = df_cleaned[(df_cleaned['InvoiceDate'] >= start_date) & (df_cleaned['InvoiceDate'] <= end_date)]


total_quantity = sales_df['Quantity'].sum()

print(f"Total quantity between {start_date} and {end_date}: {total_quantity}")

Please enter a date (YYYY-MM-DD): 2011-9-25
Please enter a date (YYYY-MM-DD): 2011-3-25
Total quantity between 2011-09-25 00:00:00 and 2011-03-25 00:00:00: 0